### ISSUE TITLE
Bash script that extracts all raw Q data from Tensorboard

### ISSUE THREAD

**Issue by philkuz** [MadcowD/openbrain#35]
Automate the process of downloading the csv of the Q plots. 

Extracts data, store in the same directory as all other datapoints.

**Comment by JamesMBartlett** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#how-can-i-export-data-from-tensorboard

**Comment by philkuz** [comment]
Add a parameter for the current experiment. Change name of summarywriter to the name. Make folder corresponding to name.
